apiVersion: v1
kind: ConfigMap
metadata:
  name: aviation-config
  namespace: aviation
data:
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "aviation_db"
  DB_USER: "aviation_user"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  ALLOWED_HOSTS: "localhost,127.0.0.1,backend-service"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://frontend-service"
  DEBUG: "False"
