apiVersion: v1
kind: Secret
metadata:
  name: aviation-secrets
  namespace: aviation
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-k8s-secret-key-change-this-in-production"
  DB_PASSWORD: "aviation_password"
  POSTGRES_PASSWORD: "aviation_password"
